// <auto-generated />
namespace EFDbFirstApproachExample.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CountryName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CountryName));
        
        string IMigrationMetadata.Id
        {
            get { return "202007081843339_CountryName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
